export enum ErrorCode {
  USER_ALREADY_EXISTS = 'USER_ALREADY_EXISTS',
  REGISTER_FAILED = 'REGISTER_FAILED',
  ADD_USER_TO_WORKSPACE_FAILED = 'ADD_USER_TO_WORKSPACE_FAILED',
  ADD_USER_TO_DEPT_FAILED = 'ADD_USER_TO_DEPT_FAILED',
  CREATE_DEPT_FAILED = 'CREATE_DEPT_FAILED',
}
